"use client";

import {useState} from "react";
import Link from "next/link";
import {StatusTag} from "@/components/ProductStates";

type State = "missing"|"input"|"verification"|"prepared"|"publication"|"published"|"pending"|"accepted"|"rejected"|"full"|"cancelled"|"replacement"|"unknown";
const states:Record<State,{label:string;title:string;happened:string;action:string;actor:string;deadline:string}>={
  missing:{label:"01 · Vehicle choice",title:"Vehicle declaration needed · sample",happened:"No current driver and vehicle declaration is selected in this preview. Historical corridor approval does not count.",action:"Open declarations and record or renew your own licence and vehicle statements. They are self-declarations, not document checks.",actor:"You record the statements; the server checks their current status before a route could be prepared.",deadline:"Before route preparation."},
  input:{label:"02 · Route input",title:"Plan a route · sample",happened:"A driver would choose one current declared vehicle, origin, destination, departure, and whole-ride seat capacity.",action:"Review your vehicle category and capacity, then submit coordinates for server verification when routing is available. This sample sends nothing.",actor:"The server verifies the route and support window after submission.",deadline:"Departure must be 2 hours to 7 days ahead, within an approved support window."},
  verification:{label:"03 · Verification failure",title:"Route could not be verified · sample",happened:"The route provider or stopping-place check could not confirm a usable route. No route was saved or published.",action:"Check the places and try again after routing returns. Do not estimate distance or contribution yourself.",actor:"The routing service and server must verify the route before preparation.",deadline:"Before any route is prepared; no decision clock has started."},
  prepared:{label:"04 · Private preparation",title:"Prepared · private · sample",happened:"A server-owned route could be saved with status prepared. It is driver-private; passengers cannot find it. This example is not a saved route.",action:"Inspect route version, vehicle, departure, capacity and deadlines. Publication remains unavailable.",actor:"The platform must open a separately approved publication path.",deadline:"Requests would close 60 minutes before departure, but there are no requests now."},
  publication:{label:"05 · Publication gate",title:"Publication unavailable",happened:"A prepared route is not a published offer. No passenger discovery or booking is open.",action:"Keep the route private and wait for launch approval. Do not share this preview as an offer.",actor:"The product owner decides after provider, policy, migration and recovery evidence.",deadline:"No launch date is approved."},
  published:{label:"06 · Future offer",title:"Published · illustrative only",happened:"No offer was published. This fixture shows how a separately authorized public offer would be identified, with a saved route version and frozen material terms after its first request.",action:"In a future live journey, inspect the published terms and incoming requests. There is no publish control here.",actor:"A passenger may request one seat before cutoff; the driver then decides.",deadline:"Sample departure 17:00 IST; requests close 16:00; decisions close 16:30."},
  pending:{label:"07 · Incoming request",title:"Incoming request · sample",happened:"One sample passenger requested one seat. Pending consumes no capacity and is not a confirmed seat.",action:"Review the ordered pickup and drop-off, server quote and deadline before accepting or rejecting. No decision can be sent here.",actor:"The driver decides; the server rechecks eligibility, terms, overlap and capacity atomically.",deadline:"Sample driver decision by 16:30 IST; unanswered requests expire then."},
  accepted:{label:"08 · Accepted",title:"Seat accepted · sample",happened:"An acknowledged acceptance would allocate one whole-ride seat and freeze route version, segment, rate, currency and integer-paise amount. No seat was allocated here.",action:"Review the recorded commitment. A lost response must be checked before assuming acceptance.",actor:"Driver and passenger follow the recorded trip details; the platform sends durable notices.",deadline:"Sample departure 17:00 IST; later journey and contribution steps remain gated."},
  rejected:{label:"09 · Rejected",title:"Request rejected · sample",happened:"A recorded rejection leaves no seat allocation. This sample made no decision.",action:"Review the recorded status before responding to another request.",actor:"The passenger may look for another route when discovery opens.",deadline:"Driver decision must be recorded by 16:30 IST in this sample."},
  full:{label:"10 · Full capacity",title:"All seats allocated · sample",happened:"The sample vehicle has one declared passenger seat and one acknowledged allocation. Pending requests alone do not fill seats.",action:"Do not accept another request unless a recorded cancellation releases capacity and the server rechecks it.",actor:"The server serializes any competing final-seat decisions.",deadline:"Decision cutoff remains 16:30 IST in this sample."},
  cancelled:{label:"11 · Cancellation",title:"Offer cancelled · sample",happened:"A driver cancellation would cancel the offer and affected commitments, with audit and notices. No real cancellation occurred.",action:"Check the acknowledged cancellation and affected bookings before planning a replacement.",actor:"The server records the cancellation; participants receive durable notices.",deadline:"Before departure for the normal cancellation path; after start requires incident review."},
  replacement:{label:"12 · Replacement",title:"Replacement route · sample",happened:"A replacement gets a new offer identity only after the earlier cancellation is acknowledged. Requests and seats do not transfer silently.",action:"Prepare a newly verified route and ask passengers to review new terms when publication is authorized.",actor:"The driver prepares; each passenger chooses whether to request again.",deadline:"New departure and decision deadlines come from the new route, not the cancelled one."},
  unknown:{label:"13 · Recovery",title:"Operation result unknown · sample",happened:"A response was lost. The action might have committed; an unknown result is not a failure or success.",action:"Look up the owner-scoped operation ID, then inspect the route or request. If no committed operation exists, retry only the original payload with the same idempotency key.",actor:"The server resolves acknowledgement or recovery; the driver checks before acting again.",deadline:"Before any retry or dependent action. There is no safe assumed deadline extension."},
};
const order=Object.keys(states) as State[];
export default function OfferRidePage(){
  const [state,setState]=useState<State>("missing");
  const [vehicle,setVehicle]=useState("bike");
  const current=states[state];
  return <div className="offer-page">
    <header className="offer-head"><div><span className="offer-eyebrow">DRIVE / PRELAUNCH</span><h1>Offer a ride</h1><p>Prepare to share your own route. Live publication and seat decisions are closed.</p></div><StatusTag tone="restricted">Real offers disabled</StatusTag></header>
    <div className="offer-banner"><strong>Current availability</strong><p>The production routing provider is unavailable. Route verification, publication, quotes, bookings, decisions and outcomes cannot be completed here.</p><Link href="/driver-vehicle-declarations">Manage declarations ↗</Link></div>
    <div className="offer-grid"><section className="offer-workspace" aria-label="Driver journey preview"><div className="offer-section-head"><span>SYNTHETIC PREVIEW / NO SERVER ACTIONS</span><h2>See the driver journey</h2><p>Switch states to inspect future decisions. Nothing in this preview is a saved route, published offer, request or booking.</p></div>
      <label className="offer-select-label" htmlFor="offer-state">Preview driver state</label><select id="offer-state" value={state} onChange={event=>setState(event.target.value as State)}>{order.map(key=><option key={key} value={key}>{states[key].label}</option>)}</select>
      <article className="offer-state" aria-live="polite"><span>{current.label.toUpperCase()}</span><h2>{current.title}</h2><dl><div><dt>What happened</dt><dd>{current.happened}</dd></div><div><dt>What you can do</dt><dd>{current.action}</dd></div><div><dt>Who acts next:</dt><dd>{current.actor}</dd></div><div><dt>By when:</dt><dd>{current.deadline}</dd></div></dl></article>
      {(state==="input"||state==="missing")&&<div className="offer-form-preview"><h3>Vehicle and route input · sample only</h3><label htmlFor="sample-vehicle">Declared vehicle category</label><select id="sample-vehicle" value={vehicle} onChange={event=>setVehicle(event.target.value)}><option value="bike">Bike · one passenger seat</option><option value="scooter">Scooter · one passenger seat</option><option value="car">Car · declared belted passenger capacity</option></select><div className="offer-input-grid"><label>Origin<input disabled value="Awaiting server routing" readOnly /></label><label>Destination<input disabled value="Awaiting server routing" readOnly /></label><label>Departure<input disabled value="Support window not approved" readOnly /></label><label>Capacity<input disabled value={vehicle==="car"?"Declared belted seats":"1 passenger"} readOnly /></label></div><p>No route input is submitted. The server must verify coordinates, mode, schedule, capacity and overlaps.</p></div>}
    </section><aside className="offer-aside"><span>TERMS / EXAMPLE ONLY</span><h2>What the driver will review</h2><div className="offer-route-art" aria-hidden="true"><i/><i/><i/></div><ul><li><b>Route:</b> server-owned geometry and version</li><li><b>Vehicle:</b> current self-declaration, never independently verified</li><li><b>Capacity:</b> whole-ride passenger seats</li><li><b>Deadline:</b> request cutoff 60 minutes before departure; driver decision 30 minutes before</li><li><b>Contribution:</b> proposed ₹5/km for bike or scooter, ₹7/km for car, no extra charge; actual segment and integer-paise amount require a server quote and remain subject to external review</li></ul><p>Historical college-corridor offers and approvals remain separate records. They do not become new-policy routes.</p></aside></div>
  </div>;
}
