"""Render the pinned local operator checklist; does not record an approval."""
from pathlib import Path
import json, hashlib, html
source=Path('apps/api/src/modules/posted-routes/service-area/review-evidence.json')
b=source.read_bytes(); d=json.loads(b); digest=hashlib.sha256(b).hexdigest()
def esc(s): return html.escape(str(s))
def link(p,label='Open contextual map'):
 return f'<a href="https://www.openstreetmap.org/?mlat={p[1]}&mlon={p[0]}#map=18/{p[1]}/{p[0]}" target="_blank" rel="noreferrer">{label}</a>'
points=''
for p in d['points']:
 points+=f'''<article><h3>{p['id']} · {esc(p['label'])}</h3><p>Requested [lon, lat]: <code>{p['requested']}</code><br>Routed [lon, lat]: <code>{p['routed']}</code><br>Car preview: P{p['id']}. {link(p['requested'])} · <a href="https://www.openstreetmap.org/way/{p['wayId']}" target="_blank" rel="noreferrer">OSM way {p['wayId']}</a></p><p>Candidate map point only. Road-side selection may differ by travel direction. No legal stopping place, local name or safety has been verified.</p><label><input type="checkbox" data-check="{p['id']}"> I reviewed this candidate's intended coverage and suitability, or recorded its rejection below.</label><textarea data-note="{p['id']}" placeholder="Local place name; map/local knowledge or field-check basis and date; approve/reject; safe/legal stop, side/direction and helmet-space observations. State any uncertainty."></textarea></article>'''
edges=''
for e in d['edges']:
 edges+=f'''<article><h3>{e['id'].title()} edge</h3><p>Inside selection: <code>{e['inside']['point']}</code> · {link(e['inside']['point'])}<br>Outside selection: <code>{e['outside']['point']}</code> · {link(e['outside']['point'])}</p><p>Actual engine route shown as “Edge {e['id']}” above. It crosses the business edge and is ineligible. These are raw illustrative provider routes, not successful application previews; their other endpoint checks are not attested.</p><label><input type="checkbox" data-check="edge-{e['id']}"> Reviewed intended inclusion/exclusion and zero-exit behavior.</label><textarea data-note="edge-{e['id']}" placeholder="Coverage implications; roads/places unexpectedly excluded; accept or reject this limit."></textarea></article>'''
reviewroutes=''
for r in d['routes']:
 reviewroutes+=f'<li><b>{r["id"]}</b> · {r["from"]} → {r["to"]} · {r["route"]["mode"]} · {r["route"]["distanceMeters"]:,} m / {r["route"]["durationSeconds"]} s · complete saved shape passes.</li>'
route_data=[dict(id=r['id'],coords=r['route']['geometry']['coordinates'],mode=r['route']['mode'],requested=r['route']['verification']['requested'],routed=r['route']['verification']['routed']) for r in d['routes']]+[dict(id='Edge '+e['id'],coords=e['route']['geometry']['coordinates'],mode='rejected',requested={'origin':e['inside']['point'],'destination':e['outside']['point']},routed={'origin':e['route']['geometry']['coordinates'][0],'destination':e['route']['geometry']['coordinates'][-1]}) for e in d['edges']]
template=r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ticket 10 · Amravati operator review</title><style>
body{font:16px/1.55 system-ui,sans-serif;background:#f4f6f5;color:#172a25;margin:0}main{max-width:1060px;margin:auto;padding:30px}h1{font-size:30px}h2{margin-top:38px}h3{margin-top:0}article,.panel{background:white;padding:22px;margin:18px 0;border:1px solid #cbd5ce;border-radius:10px}code{overflow-wrap:anywhere;font-size:13px}a{color:#11614f}textarea{box-sizing:border-box;display:block;width:100%;min-height:90px;margin:12px 0;padding:10px;font:inherit}select,button{font:inherit;padding:8px}label{display:block;margin:10px 0}input[type=checkbox]{width:18px;height:18px;vertical-align:middle;margin-right:8px}.pending{background:#fff3ce;border-left:5px solid #ae7912;padding:18px}svg{width:100%;max-height:620px;background:#f5faf8}text{font:12px system-ui;fill:#172a25}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.grid article{margin:0}@media(max-width:700px){.grid{display:block}main{padding:16px}.grid article{margin:14px 0}}#draft{min-height:220px}#route-caption{white-space:pre-wrap;overflow-wrap:anywhere;font-size:14px}button{background:#145c4b;color:white;border:0;border-radius:6px;cursor:pointer}
</style><main><h1>Amravati core · operator checklist</h1><p class="pending"><b>Review pending.</b> Implementation was authorized; meeting-place and local-route review was not attested. Completing this page prepares review notes only. It does not publish routes, enable bookings, or change the packaged approval record.</p>
<p>One review bundle for Jatin Awankar · 4 October 2026 · <code>amravati-core-v1</code>. The polygon guarantees saved coordinate containment only. It does not identify an administrative boundary, verify actual ground position, certify safe stops, or establish legal operating permission.</p>
<div class="panel"><b>Exact geometry SHA-256</b><br><code>GEOMETRY_HASH</code><p><b>Review evidence SHA-256</b><br><code>EVIDENCE_HASH</code></p><p>West/east 77.730000 / 77.830000 E; south/north 20.890000 / 20.970000 N. One original rectangular shell, no holes or islands. Original numeric business limits, independent of OSM/SOI/geoBoundaries.</p></div>
<h2>1. Inspect coverage and complete route shapes</h2><p>The diagram below is a coordinate plot of full saved routes, not a street basemap. Use the contextual map links to inspect roads and all four corners. Map/road data may be incomplete or wrong; record disagreements rather than inferring safety from a line.</p>
<p>CORNERS</p><label>Saved route <select id="route"></select></label><svg id="map" viewBox="0 0 900 720" role="img" aria-label="Amravati rectangle, five candidate meeting points and selected full route"><g id="drawing"></g></svg><p id="route-caption"></p>
<ul>ROUTE_LIST</ul><p>The eight accepted local application previews use the pinned graph and retain requested/routed endpoints and provider evidence in the bundle. R-car, R-bike and R-scooter each cover M1→M5; PM2–PM4 extend review to the other quarters. All three R routes are 6,298 m / 417 s in this graph. No live traffic is available; duration is an estimate.</p>
<label><input type="checkbox" data-check="corners"> I inspected all four sides/corners and central streets on a lawful contextual map and accept or reject their intended business coverage in my notes.</label><textarea data-note="corners" placeholder="Map/provider and review date; intended inclusions/exclusions; unfamiliar places or unresolved map errors."></textarea>
<label><input type="checkbox" data-check="routes"> I inspected all full previews, including car, bike and scooter, and the zero-exit rule is practical for the approved area.</label><textarea data-note="routes" placeholder="Per-category review; route/stopping concerns; accepted/rejected previews; review basis. Bikes/scooters use motorcycle costing, not a safety certification."></textarea>
<h2>2. Confirm or reject the five candidate meeting places</h2><p>These are agent-prepared candidates for your choice. Enter the real local name and review basis; replace a candidate if it cannot be safely identified. No field or operator review is pre-filled.</p><div class="grid">POINTS</div>
<h2>3. Review the four edge examples</h2><div class="grid">EDGES</div>
<h2>4. Confirm the rule and record a decision</h2><p>Both requested and routed endpoints must be eligible. Every saved route segment must stay inside: zero exit/re-entry, touch or edge overlap. Each raw coordinate uses [floor(10⁶x)−1, ceil(10⁶x)+1] microdegrees, strictly inside each limit; polyline6 vertices use their exact integer ±1. The one-quantum guard rejects numerical ambiguity, not GPS/road-map uncertainty. Unknown or disputed real places must be rejected or replaced with understood interior stops.</p>
<p>Keep the 50 km / 90-minute caps, explicit safe-point confirmation, maximum 30 m snap, support schedule and all existing operational/launch gates. Original authorship applies to the rectangle; road-derived preview data is © OpenStreetMap contributors under ODbL 1.0 (<a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">licence and attribution</a>). Statewide research remains unresolved and preserved.</p>
<label><input type="checkbox" data-check="rules"> I reviewed the exact hashes, original authorship, three supported categories, precision/no-exit rules, unchanged limits and limited assurance above.</label>
<label>Decision <select id="decision"><option value="pending">Pending — more review needed</option value="approve">Approve this exact coverage and reviewed candidates</option value="reject">Reject / require changes</option></select></label>
<textarea id="final-notes" placeholder="Overall decision, actual review date, support practicality, unresolved concerns and requested changes."></textarea><button id="prepare" type="button">Prepare review notes</button><p>Copy the notes below into the task after your review. Notes stay in this page until you send them; nothing is submitted or recorded automatically.</p><textarea id="draft" readonly aria-label="Prepared operator review notes"></textarea>
<p><small>Local validation only. Production gateway, deployed recovery, release and real-booking authorization remain separate gates. Edge illustrations intentionally fail service-area eligibility. No government-border or street-safety attestation is implied.</small></p></main><script>
const routes=ROUTE_DATA,points=POINT_DATA,hash='EVIDENCE_HASH';
const select=document.getElementById('route');for(const r of routes){const o=document.createElement('option');o.value=r.id;o.textContent=r.id+' · '+r.mode;select.append(o)}
const project=([lon,lat])=>[65+(lon-77.724)*6800,650-(lat-20.884)*7400];
function draw(){const r=routes.find(r=>r.id===select.value),xy=r.coords.map(project);const box=[[77.73,20.89],[77.83,20.89],[77.83,20.97],[77.73,20.97],[77.73,20.89]].map(project);let s='<polyline points="'+box.map(p=>p.join(',')).join(' ')+'" fill="#dcefe5" stroke="#37715b" stroke-width="2"/>';s+='<polyline points="'+xy.map(p=>p.join(',')).join(' ')+'" fill="none" stroke="'+(r.mode==='rejected'?'#bc422b':'#214bb7')+'" stroke-width="3"/>';for(const p of points){const [x,y]=project(p.requested);s+='<circle cx="'+x+'" cy="'+y+'" r="5" fill="#172a25"/><text x="'+(x+8)+'" y="'+(y-8)+'">'+p.id+'</text>'}for(const [i,p] of [r.coords[0],r.coords.at(-1)].entries()){const [x,y]=project(p);s+='<circle cx="'+x+'" cy="'+y+'" r="7" fill="'+(i?'#b3432c':'#208355')+'"/>'}document.getElementById('drawing').innerHTML=s;document.getElementById('route-caption').textContent=r.id+' · '+r.coords.length+' saved vertices · green start, red end · north up\nRequested [lon, lat]: '+JSON.stringify(r.requested)+'\nRouted [lon, lat]: '+JSON.stringify(r.routed);}
select.addEventListener('change',draw);draw();
document.getElementById('prepare').addEventListener('click',()=>{const lines=['Operator: Jatin Awankar','Decision: '+document.getElementById('decision').value,'Area: amravati-core-v1','Geometry: GEOMETRY_HASH','Evidence: '+hash,'Calculation: amravati-convex-microdegree-envelope-2026-10-04.1'];for(const c of document.querySelectorAll('[data-check]')){const note=document.querySelector('[data-note="'+c.dataset.check+'"]');lines.push(c.dataset.check+': '+(c.checked?'reviewed':'NOT REVIEWED')+(note?' — '+note.value:''))}lines.push('Overall notes: '+document.getElementById('final-notes').value);document.getElementById('draft').value=lines.join('\n');});
</script></html>'''
corners=' · '.join(link(p,label) for p,label in [([77.73,20.89],'SW corner'),([77.83,20.89],'SE corner'),([77.83,20.97],'NE corner'),([77.73,20.97],'NW corner')])
for key,val in {'POINTS':points,'EDGES':edges,'ROUTE_LIST':reviewroutes,'CORNERS':corners,'ROUTE_DATA':json.dumps(route_data),'POINT_DATA':json.dumps(d['points']),'GEOMETRY_HASH':d['area']['geometrySha256'],'EVIDENCE_HASH':digest}.items(): template=template.replace(key,val)
approval=json.loads(Path('apps/api/src/modules/posted-routes/service-area/operator-review.json').read_text())
if approval.get('status')=='approved':
 start=template.index('<p class="pending">'); end=template.index('</p>',start)+4
 banner='<div class="panel"><b>Actual operator map review recorded.</b><p>'+esc(approval['approver'])+' · '+esc(approval['reviewedAt'])+' (4 October 2026, 12:00 PM IST). Google Maps review; no field visit asserted.</p><p>M1: Rahat Hospital · M2: New Prabhat Colony · M3: Futka Talao · M4: Gajanan Maharaj Mandir · M5: Camp Road.</p><p>Coverage, all category previews and all four edge examples approved by the operator. No unverified items reported by the operator. This is not independent field, safety or legal verification. No deployment or real-booking activation is authorized. The form below is retained as a review template; it does not change the recorded approval.</p></div>'
 template=template[:start]+banner+template[end:]
Path('docs/operations/evidence/ticket10-amravati-operator-review-2026-10-04.html').write_text(template)
print(digest)
